<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [8]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [5]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.18.5
Pandas:  1.0.5


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [153]:
# wrong: because there's no header set
bikes = pd.read_table('../../data/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong: because it's using the second row of the table as the header
bikes = pd.read_table('../../data/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:because the column names are referred as the first line of the file
bikes = pd.read_table('../../data/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [12]:
#ANSWER:
bikes =  pd.read_csv('../../data/bikeshare.csv')
bikes

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6   
1            2  2011-01-01       1   0     1   1        0        6   
2            3  2011-01-01       1   0     1   2        0        6   
3            4  2011-01-01       1   0     1   3        0        6   
4            5  2011-01-01       1   0     1   4        0        6   
...        ...         ...     ...  ..   ...  ..      ...      ...   
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
0               0           1  0.24  0.2879  0.81     0.0000       3   
1               0           1  0.22  0.2727  0.80     0.0000       8   
2               0           1  0.22  0.2727  0.80     0.0000       5   
3               0           1  0.24  0.2879  0.75     0.0000       3   
4               0           1  0.24  0.2879  0.75     0.0000       0   
...           ...         ...   ...     ...   ...        ...     ...   
17374           1           2  0.26  0.2576  0.60     0.1642      11   
17375           1           2  0.26  0.2576  0.60     0.1642       8   
17376           1           1  0.26  0.2576  0.60     0.1642       7   
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
0              13   16  
1              32   40  
2              27   32  
3              10   13  
4               1    1  
...           ...  ...  
17374         108  119  
17375          81   89  
17376          83   90  
17377          48   61  
17378          37   49  

[17379 rows x 17 columns]

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [26]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [31]:
df = pd.read_excel('../data/Iris.xls')
df                                       

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [69]:
#ANSWER
df1 = pd.read_excel('../data/Iris.xls', skiprows = 0, header = 0, usecols=['Species_No', 'Sepal_length', 'Petal_length'], skipfooter=110)
df1

Species_No  Petal_length  Sepal_length
0            1           1.4           5.1
1            1           1.4           4.9
2            1           1.3           4.7
3            1           1.5           4.6
4            1           1.4           5.0
5            1           1.7           5.4
6            1           1.4           4.6
7            1           1.5           5.0
8            1           1.4           4.4
9            1           1.5           4.9
10           1           1.5           5.4
11           1           1.6           4.8
12           1           1.4           4.8
13           1           1.1           4.3
14           1           1.2           5.8
15           1           1.5           5.7
16           1           1.3           5.4
17           1           1.4           5.1
18           1           1.7           5.7
19           1           1.5           5.1
20           1           1.7           5.4
21           1           1.5           5.1
22           1           1.0           4.6
23           1           1.7           5.1
24           1           1.9           4.8
25           1           1.6           5.0
26           1           1.6           5.0
27           1           1.5           5.2
28           1           1.4           5.2
29           1           1.6           4.7
30           1           1.6           4.8
31           1           1.5           5.4
32           1           1.5           5.2
33           1           1.4           5.5
34           1           1.5           4.9
35           1           1.2           5.0
36           1           1.3           5.5
37           1           1.4           4.9
38           1           1.3           4.4
39           1           1.5           5.1

In [73]:
df1 = pd.read_excel('../data/Iris.xls', usecols=['Species_No', 'Sepal_width', 'Petal_width'], nrows=10)
df1

Species_No  Petal_width  Sepal_width
0           1          0.2          3.5
1           1          0.2          3.0
2           1          0.2          3.2
3           1          0.2          3.1
4           1          0.2          3.6
5           1          0.4          3.9
6           1          0.3          3.4
7           1          0.2          3.4
8           1          0.2          2.9
9           1          0.1          3.1

In [84]:
df1 = pd.read_excel('../data/Iris.xls', header = 0, skiprows=10)
df1

1  0.1  1.5  3.1  4.9      Setosa
0    1  0.2  1.5  3.7  5.4      Setosa
1    1  0.2  1.6  3.4  4.8      Setosa
2    1  0.1  1.4  3.0  4.8      Setosa
3    1  0.1  1.1  3.0  4.3      Setosa
4    1  0.2  1.2  4.0  5.8      Setosa
..  ..  ...  ...  ...  ...         ...
135  3  2.3  5.2  3.0  6.7   Verginica
136  3  1.9  5.0  2.5  6.3   Verginica
137  3  2.0  5.2  3.0  6.5   Verginica
138  3  2.3  5.4  3.4  6.2   Verginica
139  3  1.8  5.1  3.0  5.9   Verginica

[140 rows x 6 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [38]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

time   latitude   longitude  depth   mag magType   nst  \
0  2021-01-10T08:21:03.920Z  33.173832 -115.610497   2.62  3.22      ml  88.0   
1  2021-01-10T08:15:19.303Z -34.677100  -71.816700  41.53  4.70      mb   NaN   

   gap      dmin   rms  ...                   updated  \
0   36  0.005637  0.27  ...  2021-01-10T08:31:59.100Z   
1   70  0.344000  0.68  ...  2021-01-10T08:41:10.925Z   

                          place        type horizontalError depthError  \
0    10km WNW of Calipatria, CA  earthquake            0.23       0.35   
1  41 km W of Santa Cruz, Chile  earthquake            4.50       6.30   

   magError  magNst     status  locationSource magSource  
0     0.265      22  automatic              ci        ci  
1     0.081      48   reviewed              us        us  

[2 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [ ]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [37]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head() 

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [99]:
#ANSWER

#column count
print('Number of Columns in Bikes: ' + str(len(bikes.count())))
#row count
print('Number of Rows in Bikes: ' + str(len(bikes.index)))


#Alternatively 
bikes.shape

Number of Rows in Bikes: 17379
Number of Columns in Bikes: 17


(17379, 17)

What are the column names in `bikes`?

In [103]:
#ANSWER
for col in bikes.columns: 
    print(col) 

instant
dteday
season
yr
mnth
hr
holiday
weekday
workingday
weathersit
temp
atemp
hum
windspeed
casual
registered
cnt


What are the data types of these columns?

In [108]:
#ANSWER
for col in bikes.columns: 
    print(col + ':  data type' + str(type(col))) 

instant:  data type<class 'str'>
dteday:  data type<class 'str'>
season:  data type<class 'str'>
yr:  data type<class 'str'>
mnth:  data type<class 'str'>
hr:  data type<class 'str'>
holiday:  data type<class 'str'>
weekday:  data type<class 'str'>
workingday:  data type<class 'str'>
weathersit:  data type<class 'str'>
temp:  data type<class 'str'>
atemp:  data type<class 'str'>
hum:  data type<class 'str'>
windspeed:  data type<class 'str'>
casual:  data type<class 'str'>
registered:  data type<class 'str'>
cnt:  data type<class 'str'>


What is the (row) index for this DataFrame?

In [13]:
#ANSWER
bikes.index

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [14]:
#ANSWER
bikes['season'] 

type(bikes['season'])

pandas.core.series.Series

In [112]:
type(bikes[['season']])

pandas.core.frame.DataFrame

How would we use object notation to show the first 4 rows of `atemp`?

In [137]:
#ANSWER
print(bikes.atemp[0:4])

bikes.head(5)

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64


instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [144]:
#bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [149]:
#ANSWER
bikes.iloc[:1]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [15]:
#ANSWER
bikes.iloc[:,[1]]

dteday
0      2011-01-01
1      2011-01-01
2      2011-01-01
3      2011-01-01
4      2011-01-01
...           ...
17374  2012-12-31
17375  2012-12-31
17376  2012-12-31
17377  2012-12-31
17378  2012-12-31

[17379 rows x 1 columns]

## Handling Missing Values

What is the Pandas `isnull` function for? 

ANSWER: returns true or false if the value is null

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [166]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [172]:
#ANSWER
bikes.isnull().size


295443

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [196]:
#ANSWER
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [36]:
#ANSWER
def scalar_division(n, d):
    try:
        x = n/d
        print(x)
    except:
        print("Invalid output returned")

scalar_division(0,0)
scalar_division(0,1)
scalar_division(20,100)

Invalid output returned
0.0
0.2


Apply the Pandas `isna` function to the following data objects:

In [58]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


module

In [51]:
#ANSWER
x = 2.3
y = np.isnan
print(x, y)

2.3 <ufunc 'isnan'>


In [71]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [72]:
#ANSWER
for x in array:
  print(x)

[ 1. nan  3.]
[ 4.  5. nan]


How is the pandas I/O parameter `na_values` used?

? ANSWER: 

na_values parameter to consider a value to be NaN in a dataframe/table

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [83]:
#ANSWER
bikes.season.value_counts()


3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [113]:
#ANSWER
bikes.loc[:,'instant':'windspeed']

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6   
1            2  2011-01-01       1   0     1   1        0        6   
2            3  2011-01-01       1   0     1   2        0        6   
3            4  2011-01-01       1   0     1   3        0        6   
4            5  2011-01-01       1   0     1   4        0        6   
...        ...         ...     ...  ..   ...  ..      ...      ...   
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  
0               0           1  0.24  0.2879  0.81     0.0000  
1               0           1  0.22  0.2727  0.80     0.0000  
2               0           1  0.22  0.2727  0.80     0.0000  
3               0           1  0.24  0.2879  0.75     0.0000  
4               0           1  0.24  0.2879  0.75     0.0000  
...           ...         ...   ...     ...   ...        ...  
17374           1           2  0.26  0.2576  0.60     0.1642  
17375           1           2  0.26  0.2576  0.60     0.1642  
17376           1           1  0.26  0.2576  0.60     0.1642  
17377           1           1  0.26  0.2727  0.56     0.1343  
17378           1           1  0.26  0.2727  0.65     0.1343  

[17379 rows x 14 columns]

Compute and print the overall minimum and maximum of the numeric data columns:

In [120]:
bikes_min, bikes_max = (min(bikes), max(bikes))
bikes_min, bikes_max

('atemp', 'yr')

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [16]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [20]:
#ANSWER
bikes['atemp'].quantile([0.1, 0.25, 0.50, 0.75, 0.90])


0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [21]:
type(bikes['atemp'])

pandas.core.series.Series

In [22]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
6583     6584  2011-10-06       4   0    10  21        0        4           1   
7796     7797  2011-11-26       4   0    11  11        0        6           0   
6818     6819  2011-10-16       4   0    10  16        0        0           0   
2905     2906  2011-05-05       2   0     5  23        0        4           1   
4479     4480  2011-07-10       3   0     7  13        0        0           0   

      weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
6583           1  0.46  0.4545  0.88     0.0896      34         161  195  
7796           1  0.40  0.4091  0.62     0.1045     107         123  230  
6818           1  0.60  0.6212  0.46     0.3881     177         289  466  
2905           1  0.46  0.4545  0.41     0.1940      16          99  115  
4479           1  0.80  0.7273  0.46     0.2985     139         228  367

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [66]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [67]:
#ANSWER
atemp_level

0        (0.25, 0.5]
1        (0.25, 0.5]
2        (0.25, 0.5]
3        (0.25, 0.5]
4        (0.25, 0.5]
            ...     
17374    (0.25, 0.5]
17375    (0.25, 0.5]
17376    (0.25, 0.5]
17377    (0.25, 0.5]
17378    (0.25, 0.5]
Name: atemp, Length: 17379, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

Here is a random sample of `atemp_level`:

In [68]:
atemp_level.sample(5)          

14735    (0.25, 0.5]
16669    (0.25, 0.5]
7183     (0.25, 0.5]
4897     (0.5, 0.75]
1373     (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [121]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

6374     warm
1464     mild
5199      hot
12667    warm
7538     mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [131]:
#ANSWER
bikes.atemp_level = atemp_level
bikes.atemp_level.value_counts()

mild    7507
warm    7223
cool    1952
hot      697
Name: atemp, dtype: int64

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [152]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

print(a)
print(a.shape)

print(b)
print(b.shape)

print(c)
print(c.shape)

print(d)
print(d.shape)

print(e)
print(e.shape)

[0. 0. 0.]
(3,)
[[1. 1. 1.]]
(1, 3)
[[[6 1 1 5]
  [8 3 6 8]
  [5 3 7 5]]

 [[2 7 5 1]
  [6 6 4 3]
  [3 1 9 5]]]
(2, 3, 4)
[0 1 2 3]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


## Load Data

Load rock.csv and clean the dataset.

In [220]:
rock = pd.read_table('../../data/rock.csv', header=0, delimiter=',')
rock.head(5)

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [228]:
list(rock)
rock = rock.rename(columns={'Song Clean':'Song', 'ARTIST CLEAN':'Artist', 'Release Year':'Release','COMBINED':'Combined', 'First?':'First', 'Year?':'Year', 'F*G':'FG'})
rock

Song       Artist Release  \
0                                Caught Up in You  .38 Special    1982   
1                                    Fantasy Girl  .38 Special     NaN   
2                                 Hold On Loosely  .38 Special    1981   
3                          Rockin' Into the Night  .38 Special    1980   
4                               Art For Arts Sake         10cc    1975   
...                                           ...          ...     ...   
2225                      She Loves My Automobile       ZZ Top     NaN   
2226                            Tube Snake Boogie       ZZ Top    1981   
2227                                         Tush       ZZ Top    1975   
2228                                   TV Dinners       ZZ Top    1983   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO       ZZ Top    1973   

                                               Combined  First  Year  \
0                       Caught Up in You by .38 Special      1     1   
1                           Fantasy Girl by .38 Special      1     0   
2                        Hold On Loosely by .38 Special      1     1   
3                 Rockin' Into the Night by .38 Special      1     1   
4                             Art For Arts Sake by 10cc      1     1   
...                                                 ...    ...   ...   
2225                  She Loves My Automobile by ZZ Top      1     0   
2226                        Tube Snake Boogie by ZZ Top      1     1   
2227                                     Tush by ZZ Top      1     1   
2228                               TV Dinners by ZZ Top      1     1   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...      1     1   

      PlayCount   FG  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [232]:
rock.Release.isnull
rock.Release.fillna("0", inplace = True) 

#check
rock.Release.isnull

<bound method Series.isnull of 0       1982
1          0
2       1981
3       1980
4       1975
        ... 
2225       0
2226    1981
2227    1975
2228    1983
2229    1973
Name: Release, Length: 2230, dtype: object>

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [233]:
rock.dtypes

Song         object
Artist       object
Release      object
Combined     object
First         int64
Year          int64
PlayCount     int64
FG            int64
dtype: object

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [276]:
print(rock.min())
print(rock.max())

Song                        #9 Dream
Artist                   .38 Special
Release                            0
Combined     #9 Dream by John Lennon
First                              1
Year                               0
PlayCount                          0
FG                                 0
dtype: object
Song                        Ziggy Stardust
Artist                                a-ha
Release                      SONGFACTS.COM
Combined     Ziggy Stardust by David Bowie
First                                    1
Year                                     1
PlayCount                              142
FG                                     142
dtype: object


# Write Some Functions

In [257]:
def min_and_max():
    for i in rock:
        print("Name: " + i + " | Min Value: "+ str(rock[i].min()) + " | Max Value: "+ str(rock[i].max()))

min_and_max()

Name: Song | Min Value: #9 Dream | Max Value: Ziggy Stardust
Name: Artist | Min Value: .38 Special | Max Value: a-ha
Name: Release | Min Value: 0 | Max Value: SONGFACTS.COM
Name: Combined | Min Value: #9 Dream by John Lennon | Max Value: Ziggy Stardust by David Bowie
Name: First | Min Value: 1 | Max Value: 1
Name: Year | Min Value: 0 | Max Value: 1
Name: PlayCount | Min Value: 0 | Max Value: 142
Name: FG | Min Value: 0 | Max Value: 142


## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [308]:
def print_release():
    for row in rock.iterrows():
         if int(row[1].Release) < 1970:
          print("Song: " + str(row[1].Song) + " | Artist: " + row[1].Artist)

print_release()

Song: Fantasy Girl | Artist: .38 Special
Song: Baby, Please Don't Go | Artist: AC/DC
Song: CAN'T STOP ROCK'N'ROLL | Artist: AC/DC
Song: Girls Got Rhythm | Artist: AC/DC
Song: Let's Get It Up | Artist: AC/DC
Song: Live Wire | Artist: AC/DC
Song: Moneytalks | Artist: AC/DC
Song: Shoot To Thrill | Artist: AC/DC
Song: Sin City | Artist: AC/DC
Song: What Do You Do For Money Honey | Artist: AC/DC
Song: Baby, Please Don't Go | Artist: Aerosmith
Song: Come Together | Artist: Aerosmith
Song: Kings and Queens | Artist: Aerosmith
Song: One Way Street | Artist: Aerosmith
Song: The Other Side | Artist: Aerosmith
Song: You See Me Crying | Artist: Aerosmith
Song: Fantasy | Artist: Aldo Nova
Song: BE MY LOVER | Artist: Alice Cooper
Song: House Of Fire | Artist: Alice Cooper
Song: One Way Out | Artist: Allman Brothers Band
Song: Southbound | Artist: Allman Brothers Band
Song: Whippin' Post | Artist: Allman Brothers Band
Song: Don't Bring Me Down | Artist: Animals II
Song: Don't Let Me Be Misunderstood 

ValueError: invalid literal for int() with base 10: 'SONGFACTS.COM'

## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

## Apply these functions to your dataset

## Describe the new float-only DataFrame.



> 
>
>




>


>


>




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



